### ISSUE TITLE
Question: What happens when I click publish?

### ISSUE THREAD

**Issue by zjuchenyuan** [kpcyrd/ipfs.ink#5]
Thank you for your devotion to this amazing app.

I'm new to ipfs, and have some basic question about ipfs and this app.

When I write a markdown document, and click the "publish" button, I know this document will be added to ipfs p2p network. And when user visit share link like `ipfs.ink/e/...` may be first querying your server local repo to retrieve the document.

But how many nodes in the network will have this document? 

What if your server break down or just go away, can I retrieve the document back?

I want to achieve high availability for my documents,  for example, years later I still wanna to be able to get my document back. What can I do for this goal? Maybe setup my own ipfs node and pin the documents?

Thanks a lot if you can help me better understand ipfs!

**Comment by zjuchenyuan** [comment]
It seems that I have found answers to these questions.

### how many nodes in the network will have this document?

ipfs nodes will only store and share content they actively pulled, so after click `publish`, only 1 node (`ipfs.ink` server) will have the content.

If you visit `ipfs.io/ipfs/...` or other public gateway after publish, the gateway will save temporary copy of the document for free for a while

### how to enhance the availability?

There are paied IPFS pinning services, like [eternum.io](https://www.eternum.io/), or [pinbits.io](https://pinbits.io/)

And have a look at https://github.com/ipfs/faq/issues/239

**Comment by kpcyrd** [comment]
hey @zjuchenyuan. :) Your conclusion is correct. The document is automatically pinned by the ipfs.ink server and there are daily backups, but it's a good idea to pin the document yourself as well (or have somebody else pin it for you). If ipfs.ink ceases to exist, it's possible to recover the document, given that there's at least one other user who still has that document.
